Repository lab-brussels-1/Group-1-Project-Management, pull requests merged in 2022-03, with the labels that each got.

#11 Adding "people" folder
  .github/workflows/lint.yml
  _config.yml
  people/mariabio.md
Labels: documentation

#15 Changed path for the image
  people/mariabio.md
Labels: md

#18 Madhu
  photos/.DS_Store
  photos/cd
  photos/madhu.jpg
Labels: documentation

#20 Nazgulbio
  people/nazgulbio.md
  photos/programmer.png
  photos/space.gif
Labels: md, first issue

#22 Haneefa shaik Bio
  README.md
  people/haneefa-shaik.md
  photos/Hello.gif
Labels: md, first issue

#24 modified the bio
  people/madhubio.md
Labels: enhancement

#28 using relative paths for the images
  people/fennybio.md
  people/madhubio.md
  people/mariabio.md
  people/nazgulbio.md
Labels: enhancement, md

#29 use "../photos/Hello.gif" instead of "/photos/Hello.gif" when using a…
  people/haneefa-shaik.md
Labels: enhancement
